name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04
    container: clojure:openjdk-17-tools-deps-1.11.0.1100-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Clojars
        uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
